#! /usr/bin/env sh

##########################
# wm independent hotkeys #
##########################

# Terminal emulator
super + shift + Return
  kitty

# Browser
super + b
  firefox

# Filemanager
super + n
  nautilus

# Rofi apps menu
super + d
  ~/scripts/appsmenu.sh

# Power
super + 0
  ~/scripts/powermenu.sh

# Lock
super + l
  ~/scripts/lock.sh

# Network menu
super + shift + n
  networkmenu

# Scratchpad
super + Return
  ~/.config/bspwm/scripts/toggle_scratchpad.sh

Super_L
  polybar-msg cmd show
@Super_L
  polybar-msg cmd hide

XF86MonBrightness{Up,Down}
	xbacklight {+,-} 10

XF86Audio{Mute,RaiseVolume,LowerVolume}
  ~/scripts/volume.sh {mute,up,down}

Print
  flameshot gui

#################
# bspwm hotkeys #
#################

# quit/restart bspwm
super + shift + slash
	bspc wm -r

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest local node
super + g
	bspc node -s biggest.local

# Focus to a given desktop
super + Escape
  bspc query -D -d "^1.focused" && bspc desktop -f last || bspc desktop -f "^1"
super + {1-8}
  desktop='^{2-9}'; \
  bspc query -D -d "$desktop.focused" && bspc desktop -f last || bspc desktop -f "$desktop"

# Send to a given desktop
super + shift + Escape
  bspc node -d '^1' --follow
super + shift + {1-8}
  bspc node -d '^{2-9}' --follow

# Rotate nodes
super + {_,shift + }r
  bspc node -f @parent; bspc node -R {_,-}90

###############
# state/flags #
###############

# Toggle fullscreen
super + f
  bspc node -t \~fullscreen

# Set the window state
super + {t,shift + t,s}
	bspc node -t {tiled,pseudo_tiled,floating}

# Set the window state to floating
super + space
	bspc node -t floating

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

##############
# focus/swap #
##############

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

#############
# preselect #
#############

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}
super + ctrl + {Left,Down,Up,Right}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel
~Escape
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

###############
# move/resize #
###############

# expand a window by moving one of its side outward
# super + alt + {h,j,k,l}
  # bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}
# super + alt + {Left,Down,Up,Right}
  # bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
  ~/scripts/resize.sh {west, south, north, east}
super + alt + {Left,Down,Up,Right}
  ~/scripts/resize.sh {west, south, north, east}

# # contract a window by moving one of its side inward
# super + alt + shift + {Left,Down,Up,Right}
  # bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

########
# rice #
########

# Focused desktop window gap
super + shift + button{4,5}
    bspc config -d focused window_gap $((`bspc config -d focused window_gap` {-,+} 2 ))

# Global window gaps
super + shift + ctrl + button{4,5}
    bspc config window_gap $(( $(bspc config window_gap) {-,+} 2 ))

# Return to default
super + shift + d
  bspc config border_width 1; bspc config window_gap 0;
