#! /bin/sh

# Background
feh --bg-center ~/Pictures/Wallpapers/gruvbox.png

picom -b &
sxhkd &
flameshot &
xfce4-power-manager &
dunst -conf ~/.config/dunst/dunstrc &
lxsession &

# Restore audio to the correct state

bspc monitor -d λ 1 2 3 4 5 6 7 8

bspc config border_width        1
bspc config window_gap          0
bspc config focused_border_color 	"#d5c4a1"

bspc config split_ratio           0.61
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle 	      true

bspc config focus_by_distance     true
bspc config focus_follows_pointer true
bspc config history_aware_focus   true
bspc config pointer_follows_focus false

bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side

bspc config automatic_scheme      longest_side

bspc rule -a jetbrains-pycharm desktop='^4' follow=off
bspc rule -a Gpick state=floating sticky=on
bspc rule -a Mullvad\ VPN state=pseudo_tiled desktop='^8' follow=off
bspc rule -a firefox desktop='^2' follow=off

bspc config external_rules_command "~/scripts/external_rules.sh"

# Open default apps
bspc desktop='^2' --focus
firefox &

# Open terminal on first desktop
bspc desktop='^1'
kitty &

# Polybar
~/.config/polybar/launch.sh

