#! /bin/sh
bspc monitor -d λ 1 2 3 4 5 6 7 8

bspc config border_width        1
bspc config window_gap          0
bspc config focused_border_color 	"#d5c4a1"

bspc config split_ratio           0.61
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle 	      true

bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc rule -a jetbrains-pycharm desktop='^4'
bspc rule -a Gpick state=floating sticky=on

# Background
feh --bg-center ~/Pictures/Wallpapers/gruvbox.jpg

$HOME/.config/polybar/launch.sh

# Needed for pycharm
wmname LG3D

# Restore audio to the correct state
alsactl --file ~/.config/asound.state restore

dunst -conf ~/.config/dunst/dunstrc &
compton &
sxhkd &
